function annotatePmaxFigure(figure1)
%CREATETEXTARROW(figure1)
%  FIGURE1:  annotation figure

%  Auto-generated by MATLAB on 03-Dec-2020 16:31:12

% Create textarrow
annotation(figure1,'textarrow',...
    [0.161666666666667 0.133333333333333],[0.869 0.85],...
    'String',{'T_{max}'});

annotation(figure1,'textarrow',[0.385 0.425],[0.747 0.718],...
    'String',{'H_{opt}'});

annotation(figure1,'textarrow',[0.35 0.343333333333333],...
    [0.623 0.586],'String',{'C_{max}'});

annotation(figure1,'textarrow',[0.6 0.58],[0.836 0.808],...
    'String',{'P_{max}'});

annotation(figure1,'textarrow',[0.701666666666667 0.68],...
    [0.623 0.592],'String',{'C_{opt}'});

end

